Traceback (most recent call last):
  File "/home/obm/Prog/miniconda3/envs/qiskit/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/obm/Prog/miniconda3/envs/qiskit/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/obm/Prog/miniconda3/envs/qiskit/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/obm/Prog/miniconda3/envs/qiskit/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/obm/Prog/miniconda3/envs/qiskit/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/obm/Prog/miniconda3/envs/qiskit/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/obm/Prog/miniconda3/envs/qiskit/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/obm/Prog/miniconda3/envs/qiskit/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
qc.cx(0,1)
display(qc.draw())

qc.save_statevector('mpl')
qobj = assemble(qc)
final_state = svsim.run(qobj).result().get_statevector()
display(array_to_latex(final_state, prefix="\\text{Statevector} = "))
plot_bloch_multivector(final_state)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m~/Prog/miniconda3/envs/qiskit/lib/python3.8/site-packages/qiskit/result/result.py:325[0m, in [0;36mResult.get_statevector[0;34m(self, experiment, decimals)[0m
[1;32m    323[0m [38;5;28;01mtry[39;00m:
[1;32m    324[0m     [38;5;28;01mreturn[39;00m postprocess[38;5;241m.[39mformat_statevector(
[0;32m--> 325[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdata[49m[43m([49m[43mexperiment[49m[43m)[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mstatevector[39;49m[38;5;124;43m"[39;49m[43m][49m, decimals[38;5;241m=[39mdecimals
[1;32m    326[0m     )
[1;32m    327[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m ex:

[0;31mKeyError[0m: 'statevector'

The above exception was the direct cause of the following exception:

[0;31mQiskitError[0m                               Traceback (most recent call last)
Input [0;32mIn [23][0m, in [0;36m<cell line: 6>[0;34m()[0m
[1;32m      4[0m qc[38;5;241m.[39msave_statevector([38;5;124m'[39m[38;5;124mmpl[39m[38;5;124m'[39m)
[1;32m      5[0m qobj [38;5;241m=[39m assemble(qc)
[0;32m----> 6[0m final_state [38;5;241m=[39m [43msvsim[49m[38;5;241;43m.[39;49m[43mrun[49m[43m([49m[43mqobj[49m[43m)[49m[38;5;241;43m.[39;49m[43mresult[49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mget_statevector[49m[43m([49m[43m)[49m
[1;32m      7[0m display(array_to_latex(final_state, prefix[38;5;241m=[39m[38;5;124m"[39m[38;5;130;01m\\[39;00m[38;5;124mtext[39m[38;5;132;01m{Statevector}[39;00m[38;5;124m = [39m[38;5;124m"[39m))
[1;32m      8[0m plot_bloch_multivector(final_state)

File [0;32m~/Prog/miniconda3/envs/qiskit/lib/python3.8/site-packages/qiskit/result/result.py:328[0m, in [0;36mResult.get_statevector[0;34m(self, experiment, decimals)[0m
[1;32m    324[0m     [38;5;28;01mreturn[39;00m postprocess[38;5;241m.[39mformat_statevector(
[1;32m    325[0m         [38;5;28mself[39m[38;5;241m.[39mdata(experiment)[[38;5;124m"[39m[38;5;124mstatevector[39m[38;5;124m"[39m], decimals[38;5;241m=[39mdecimals
[1;32m    326[0m     )
[1;32m    327[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m ex:
[0;32m--> 328[0m     [38;5;28;01mraise[39;00m QiskitError([38;5;124mf[39m[38;5;124m'[39m[38;5;124mNo statevector for experiment [39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;28mrepr[39m(experiment)[38;5;132;01m}[39;00m[38;5;124m"[39m[38;5;124m'[39m) [38;5;28;01mfrom[39;00m [38;5;21;01mex[39;00m

[0;31mQiskitError[0m: 'No statevector for experiment "None"'
QiskitError: 'No statevector for experiment "None"'

